# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array= np.array([12, 10, 15, 16, 21])
print("array:", array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sıralama = np.sort(array)
print("sıralanmış array:", sıralama)


array: [12 10 15 16 21]
sıralanmış array: [10 12 15 16 21]


# Problem 2

In [3]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array1 = np.array([10,15,30,45,60])
print("array1:", array1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2= np.arange(5, 16)
print("array2:", array2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3= np.arange(50, 101, 5)
print("array3:", array3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4= np.zeros(10)
print("array4:", array4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5= np.ones(10)
print("array5:", array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6= np.linspace(0, 100, 5)
print("array6:", array6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7= np.random.randint(10, 31, 5)
print("array7:", array7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8= np.random.uniform(-1,1,10)
print("array8:", array8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris9= np.random.randint(10,51, (3,5))
print("matris9:\n", matris9)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
toplam= matris9.shape[0]+matris9.shape[1]
print("satır ve sütun toplamları:", toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk= np.max(matris9)
print("en büyük değer:", en_buyuk)
en_kucuk= np.min(matris9)
print("en küçük değer:", en_kucuk)
ortalama= np.mean(matris9)
print("ortalama:", ortalama)
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
en_buyuk_index= np.argmax(matris9)
print("en büyük değerin indeksi:", en_buyuk_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array13= np.arange(10, 20)
ilk3= array13[:3]
print("ilk 3 eleman:", ilk3)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
tersarray= array13[::-1]
print("ters array:", tersarray)

# 15- Üretilen matrisin ilk satırını seçiniz.
ilk_satir= matris9[0, :]
print("ilk satır:", ilk_satir)
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman2_3= matris9[1,2]
print("2. ve 3. sütun elemanı:", eleman2_3)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilk_eleman=matris9[:,0]
print("ilk elemanlar:", ilk_eleman)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
kare=np.square(matris9)
print("kareleri:\n", kare)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris19= np.random.randint(-50,51, (3,5))
pozitif= matris19[(matris19> 0) & (matris19 % 2== 0)]
print("pozitif çift sayılar:", pozitif)

array1: [10 15 30 45 60]
array2: [ 5  6  7  8  9 10 11 12 13 14 15]
array3: [ 50  55  60  65  70  75  80  85  90  95 100]
array4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array6: [  0.  25.  50.  75. 100.]
array7: [28 10 28 16 16]
array8: [ 0.74088669  0.22646383  0.01067008  0.49780127  0.19700861  0.94904277
  0.48408213 -0.74146293  0.11326694  0.22903598]
matris9:
 [[26 37 19 29 28]
 [11 20 29 26 27]
 [29 30 50 23 15]]
satır ve sütun toplamları: 8
en büyük değer: 50
en küçük değer: 11
ortalama: 26.6
en büyük değerin indeksi: 12
ilk 3 eleman: [10 11 12]
ters array: [19 18 17 16 15 14 13 12 11 10]
ilk satır: [26 37 19 29 28]
2. ve 3. sütun elemanı: 29
ilk elemanlar: [26 11 29]
kareleri:
 [[ 676 1369  361  841  784]
 [ 121  400  841  676  729]
 [ 841  900 2500  529  225]]
pozitif çift sayılar: [12 34 46 46]
